### ISSUE TITLE
Add the ability for Users to add movies

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/Movie#7]

**Comment by erfanasadi** [comment]
can i work on this?

**Comment by samuel-ma** [comment]
Sure thing, there's a plus button on the bottom right and a model that pops up when the button is clicked
The goal is to add a new movie each time the user fills in the form and clicks add on the model

**Comment by erfanasadi** [comment]
i create it please watch it

**Comment by samuel-ma** [comment]
@erfanasadi 
thanks for the help
I'll merge your pull request
